service: my-todos-gateway-gql

provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: false
  region: us-east-1
  apiGateway:
    shouldStartNameWithService: true

custom:
  serverless-offline:
    httpPort: 4000
    websocketPort: 4001
    lambdaPort: 4002

functions:
  graphql:
    handler: build/server.handler
    events:
      - http:
          path: graphql
          method: any
          cors: true

plugins:
  - serverless-offline
